#!/usr/bin/env node
/**
 * Emits the two platform shapes of the token set from `src/tokens.ts`.
 *
 * Run with `npm run generate --workspace @word-lock/tokens`. The output is
 * committed rather than built on demand, for two reasons: `globals.css` has to
 * be able to `@import` a real file during a Tailwind build with no extra build
 * step in front of it, and a committed artifact means a token change shows up as
 * a reviewable diff in colours rather than as an invisible change in a script.
 *
 * `tokens.test.ts` asserts the committed files match what this script would
 * write, so a forgotten regeneration fails CI instead of shipping.
 *
 * Needs Node >= 22.6 for `--experimental-strip-types`, which is how it imports
 * the TypeScript source directly. The alternative was compiling the package
 * first, which would have put a build step in front of every Tailwind run.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

import { RADIUS, TOKEN_GROUPS, isRef, isThemed, resolve } from "../src/tokens.ts";
import { overshootOf, toNativeColor } from "../src/color.ts";

const PACKAGE_ROOT = path.resolve(import.meta.dirname, "..");
const OUT_DIR = path.join(PACKAGE_ROOT, "generated");

const BANNER_LINES = [
  "Generated by packages/tokens/scripts/generate.mjs — do not edit.",
  "",
  "Edit packages/tokens/src/tokens.ts and re-run:",
  "  npm run generate --workspace @word-lock/tokens",
];

/** Wraps a note at roughly the prettier print width, as a CSS block comment. */
function cssComment(text, indent) {
  const width = 100 - indent.length - 3;
  const words = text.split(/\s+/);
  const lines = [];
  let line = "";
  for (const word of words) {
    if (line && `${line} ${word}`.length > width) {
      lines.push(line);
      line = word;
    } else {
      line = line ? `${line} ${word}` : word;
    }
  }
  if (line) lines.push(line);

  if (lines.length === 1) return `${indent}/* ${lines[0]} */\n`;
  return `${indent}/*\n` + lines.map((l) => `${indent} * ${l}\n`).join("") + `${indent} */\n`;
}

function declaration(token, theme, indent) {
  const raw = isThemed(token.value) ? token.value[theme] : token.value;
  const text = isRef(raw) ? `var(--${raw.ref})` : raw;
  return `${indent}--${token.name}: ${text};\n`;
}

/* ---------------------------------------------------------------------------
 * generated/tokens.css
 * ------------------------------------------------------------------------- */
function buildCss() {
  let out =
    "/*\n" +
    BANNER_LINES.map((l) => ` * ${l}\n`)
      .join("")
      .replace(/ \* \n/g, " *\n") +
    " */\n\n";

  out += ":root {\n";
  out += `  --radius: ${RADIUS};\n`;
  for (const group of TOKEN_GROUPS) {
    out += "\n";
    if (group.heading) out += cssComment(group.heading, "  ");
    for (const token of group.tokens) {
      if (token.note) out += cssComment(token.note, "  ");
      out += declaration(token, "light", "  ");
    }
  }
  out += "}\n";

  /*
   * Only tokens that actually differ are emitted into `.dark`. A themed token
   * whose two values are identical would be a redundant declaration — the old
   * hand-written stylesheet had two of those (`--ring`, `--on-accent`), and
   * they are modelled as theme-invariant here instead.
   */
  out += "\n.dark {\n";
  let first = true;
  for (const group of TOKEN_GROUPS) {
    const themed = group.tokens.filter((t) => isThemed(t.value));
    if (themed.length === 0) continue;
    if (!first) out += "\n";
    first = false;
    if (group.heading) out += cssComment(group.heading, "  ");
    for (const token of themed) {
      out += declaration(token, "dark", "  ");
    }
  }
  out += "}\n";

  return out;
}

/* ---------------------------------------------------------------------------
 * generated/tokens.native.ts
 * ------------------------------------------------------------------------- */
function buildNative() {
  const remMatch = /^([\d.]+)rem$/.exec(RADIUS);
  if (!remMatch) {
    throw new Error(`RADIUS is "${RADIUS}"; the native emitter only understands rem.`);
  }
  // 1rem is 16px on both platforms' defaults. React Native has no rem unit, so
  // the scale has to be emitted in points.
  const radiusPx = parseFloat(remMatch[1]) * 16;

  const camel = (name) => name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

  let out =
    "/*\n" +
    BANNER_LINES.map((l) => ` * ${l}\n`)
      .join("")
      .replace(/ \* \n/g, " *\n") +
    " */\n\n";
  out += "/* eslint-disable */\n\n";
  out +=
    "/**\n" +
    " * Every token resolved to something React Native can consume: `#rrggbb`,\n" +
    " * `rgba(...)` or the `transparent` keyword. `oklch()` and CSS custom\n" +
    " * properties do not exist here, so the conversion happens at generate time\n" +
    " * rather than at runtime.\n" +
    " *\n" +
    " * Values marked `clamped` were authored outside the sRGB gamut. A browser on\n" +
    " * a P3 display shows those as authored; React Native has no portable\n" +
    " * wide-gamut colour input, so the app gets the nearest sRGB colour and those\n" +
    " * swatches are genuinely a little less vivid on a phone. The player colours\n" +
    " * are among them, so this is a visible difference rather than a pedantic one.\n" +
    " */\n";

  for (const theme of ["light", "dark"]) {
    out += `export const ${theme}Colors = {\n`;
    for (const group of TOKEN_GROUPS) {
      for (const token of group.tokens) {
        const source = resolve(token.name, theme);
        const overshoot = overshootOf(source);
        const annotation =
          overshoot > 0.001 ? ` // clamped from ${source} (overshoot ${overshoot.toFixed(3)})` : "";
        out += `  "${camel(token.name)}": "${toNativeColor(source)}",${annotation}\n`;
      }
    }
    out += "} as const;\n\n";
  }

  out += "export type ColorName = keyof typeof lightColors;\n\n";
  out += "export const colors = { light: lightColors, dark: darkColors } as const;\n\n";

  /*
   * The camelCase key above and the custom property `tokens.native.css`
   * declares are *not* mechanically interconvertible, which is why this map is
   * emitted rather than reconstructed by the consumer. `camel()` above turns
   * `surface-2` into `surface2`, since the uppercase of a digit is itself — so
   * a naive camel-to-kebab pass on the way back produces `--surface2`, a
   * variable nothing declares, and it cannot simply split letter/digit
   * boundaries either because `--p1` and `--p2` are authored without a hyphen.
   * Only the generator sees both spellings, so only the generator can pair
   * them. `apps/mobile/tailwind.config.js` is the consumer.
   */
  out +=
    "/**\n" +
    " * Each token's camelCase key paired with the custom property\n" +
    " * `generated/tokens.native.css` declares for it. Use this to build a\n" +
    " * `var(--name)` reference; do not re-derive the name from the key.\n" +
    " */\n";
  out += "export const cssVarNames = {\n";
  for (const group of TOKEN_GROUPS) {
    for (const token of group.tokens) {
      out += `  "${camel(token.name)}": "--${token.name}",\n`;
    }
  }
  out += "} as const satisfies Record<ColorName, string>;\n\n";
  out +=
    "/** `--radius` in points. The web derives its whole radius scale from this. */\n" +
    `export const RADIUS_BASE_PX = ${radiusPx};\n\n`;
  out +=
    "export const radius = {\n" +
    `  sm: ${radiusPx - 2},\n` +
    `  md: ${radiusPx},\n` +
    `  lg: ${radiusPx + 2},\n` +
    `  xl: ${radiusPx + 4},\n` +
    `  "2xl": ${radiusPx + 6},\n` +
    `  "3xl": ${radiusPx + 8},\n` +
    `  "4xl": ${radiusPx + 10},\n` +
    "} as const;\n";

  return out;
}

/* ---------------------------------------------------------------------------
 * generated/tokens.native.css
 * ------------------------------------------------------------------------- */
/**
 * The `:root`/`.dark` custom-property blocks NativeWind resolves at runtime
 * (see https://nativewind.dev/docs/guides/themes) — the same mechanism
 * `tokens.css` gives the web app, but with every value pre-resolved to sRGB
 * hex/`rgba()` instead of `oklch()`, which NativeWind's CSS-variable runtime
 * cannot parse any more than plain React Native can. This is why it is not
 * simply `tokens.css` reused: the *notation*, not just the consumer, has to
 * change.
 *
 * Plain v3-safe CSS: no `@theme inline`, no `@custom-variant`.
 *
 * The dark block is a `@media (prefers-color-scheme: dark)` wrapper around
 * `:root`, where the web's `tokens.css` uses a bare `.dark`. That difference is
 * load-bearing rather than cosmetic, and the media query is **not** a statement
 * that the app follows the OS setting — `ThemeProvider.tsx`'s manual override
 * still works. Here is why both halves of that are true.
 *
 * NativeWind recognises variable declarations only from a fixed set of
 * selectors — see `normalizeSelectors` in
 * `react-native-css-interop/src/css-to-rn/normalize-selectors.ts`, whose
 * matchers are `:root`, `@media(prefers-color-scheme: dark) { :root }`,
 * `.dark:root`, `:root[class~="dark"]`, `*` and `.dark *`. A bare
 * `.dark { --x: … }` matches none of them, so it compiles to an ordinary style
 * rule for elements whose className is literally "dark" — nothing in the app —
 * and the whole dark palette is dropped.
 *
 * `.dark:root` looks like the fix and is not, because it is only recognised
 * once the extractor already knows dark mode is class-based:
 * `isRootDarkVariableSelector` returns false unless `options.darkMode.type ===
 * "class"`, and that option starts life as `{ type: "media" }`
 * (`css-to-rn/index.ts`) and is only switched by the `@cssInterop set darkMode
 * class dark` at-rule that NativeWind's own plugin emits through `addBase`.
 * `addBase` output lands in the `@tailwind base` layer, and `globals.css` has to
 * `@import` this file *above* the `@tailwind` directives or `postcss-import`
 * refuses to inline it at all. So the dark block is always parsed a couple of
 * hundred lines before the flag that would make it legible — verify with
 * `NATIVEWIND_OS=ios npx tailwindcss -i src/app/globals.css -o /tmp/out.css` and
 * compare the line numbers of `.dark:root` and `@cssInterop set darkMode`.
 *
 * The media query has no such dependency: that branch of `normalizeSelectors`
 * reads nothing but the selector and the query itself. And the query is
 * evaluated at *parse* time, not at runtime — `setStyleForSelectorList` files
 * these declarations into `rootVariables` keyed by `subtype: "dark"` and
 * discards `extractedStyle.media` for the `rootVariables` branch entirely. Which
 * subtype is live afterwards is decided by NativeWind's colorScheme observable,
 * i.e. by `setColorScheme`, i.e. by `ThemeProvider`. Choosing "light" on a
 * device set to dark still works.
 *
 * Getting this wrong does not crash and does not leave a colour blank, which is
 * why it needs this much comment: the interop's per-variable dark observable
 * falls back to the light value (`cssVariableObservable` in
 * `runtime/native/appearance-observables.ts`), so the app renders the *light*
 * palette in dark mode, right next to the correct dark values wherever a
 * component reads `colors[resolvedTheme]` from `tokens.native.ts` directly.
 */
function buildNativeCss() {
  let out =
    "/*\n" +
    BANNER_LINES.map((l) => ` * ${l}\n`)
      .join("")
      .replace(/ \* \n/g, " *\n") +
    " */\n\n";

  const remMatch = /^([\d.]+)rem$/.exec(RADIUS);
  if (!remMatch) {
    throw new Error(`RADIUS is "${RADIUS}"; the native CSS emitter only understands rem.`);
  }
  const radiusPx = parseFloat(remMatch[1]) * 16;
  const radiusScale = {
    sm: radiusPx - 2,
    md: radiusPx,
    lg: radiusPx + 2,
    xl: radiusPx + 4,
    "2xl": radiusPx + 6,
    "3xl": radiusPx + 8,
    "4xl": radiusPx + 10,
  };

  out += ":root {\n";
  for (const [name, px] of Object.entries(radiusScale)) {
    out += `  --radius-${name}: ${px}px;\n`;
  }
  for (const group of TOKEN_GROUPS) {
    out += "\n";
    if (group.heading) out += cssComment(group.heading, "  ");
    for (const token of group.tokens) {
      if (token.note) out += cssComment(token.note, "  ");
      out += `  --${token.name}: ${toNativeColor(resolve(token.name, "light"))};\n`;
    }
  }
  out += "}\n";

  // A media-wrapped `:root`, not `.dark` and not `.dark:root` — see this
  // function's doc comment for why each of those two fails, and why this one
  // does not mean "follow the OS". Only tokens that actually differ are
  // emitted; the interop falls each undeclared dark variable back to its light
  // value on its own.
  out += "\n@media (prefers-color-scheme: dark) {\n";
  out += "  :root {\n";
  let first = true;
  for (const group of TOKEN_GROUPS) {
    const themed = group.tokens.filter((t) => isThemed(t.value));
    if (themed.length === 0) continue;
    if (!first) out += "\n";
    first = false;
    if (group.heading) out += cssComment(group.heading, "    ");
    for (const token of themed) {
      out += `    --${token.name}: ${toNativeColor(resolve(token.name, "dark"))};\n`;
    }
  }
  out += "  }\n";
  out += "}\n";

  return out;
}

export const artifacts = {
  "tokens.css": buildCss(),
  "tokens.native.ts": buildNative(),
  "tokens.native.css": buildNativeCss(),
};

function main() {
  mkdirSync(OUT_DIR, { recursive: true });
  for (const [name, contents] of Object.entries(artifacts)) {
    const target = path.join(OUT_DIR, name);
    writeFileSync(target, contents, "utf8");
    console.log(`wrote ${path.relative(PACKAGE_ROOT, target)} (${contents.length} bytes)`);
  }
}

if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) {
  main();
}
